const http = require('http');
const fs = require('fs');
const path = require('path');
const logger = require('./logger');
const { fetchAllAuctions, fetchMyBudget } = require('./auctions');
const { createAuction, createAutoGeneratedAuctions, maintainAuctionInventory } = require('./seller');
const { bidOnEligibleAuctions, finalizeAuction, placeBid } = require('./bidder');
const { processClosedAuctions } = require('./winner');
const { getAccount, getWeb3, getFactory, getFactoryAddress, weiToEth, retryRpc, unwrapError, resyncNonce } = require('./chain');
const { getRuntimeConfig, updateRuntimeConfig } = require('./config');
const { startListening } = require('./listener');

const PORT = parseInt(process.env.ADMIN_PORT || '3002', 10);

const botState = {
  running: false,
  cronHandle: null,
  lastCycle: null,
  cycleCount: 0,
  log: [],
  stats: { bids: 0, created: 0, finalized: 0, errors: 0 },
  statusCache: null,
  listenerStarted: false,
  cycleRunning: false,
  marketCache: null,
  marketCacheAt: 0,
};

const MARKET_CACHE_TTL_MS = 8000;

const baseInfo = logger.info.bind(logger);
const baseWarn = logger.warn.bind(logger);
const baseError = logger.error.bind(logger);

function pushLog(level, message) {
  botState.log.unshift({
    time: new Date().toISOString(),
    level,
    msg: typeof message === 'object' ? JSON.stringify(message) : String(message),
  });
  if (botState.log.length > 250) botState.log.length = 250;
}

logger.info = (message, ...rest) => { pushLog('info', message); baseInfo(message, ...rest); };
logger.warn = (message, ...rest) => { pushLog('warn', message); baseWarn(message, ...rest); };
logger.error = (message, ...rest) => { pushLog('error', message); baseError(message, ...rest); };

function json(res, data, status = 200, corsHeaders = {}) {
  res.writeHead(status, { 'Content-Type': 'application/json', ...corsHeaders });
  res.end(JSON.stringify(data, null, 2));
}

async function handleApi(req, res, body, cors) {
  const url = new URL(req.url, `http://localhost:${PORT}`);
  const endpoint = url.pathname;
  const forceRefresh = url.searchParams.get('refresh') === '1';

  if (req.method === 'GET' && endpoint === '/api/status') {
    const account = getAccount();
    try {
      const balance = await retryRpc(() => getWeb3().eth.getBalance(account.address));
      const budget = await fetchMyBudget();
      const auctions = botState.marketCache || [];
      const payload = {
        wallet: account.address,
        balanceETH: weiToEth(balance.toString()),
        budgetWei: budget.toString(),
        auctionCount: auctions.length,
        openAuctions: auctions.filter((a) => a.isActive).length,
        botRunning: botState.running,
        lastCycle: botState.lastCycle,
        cycleCount: botState.cycleCount,
        stats: botState.stats,
        config: getRuntimeConfig(),
      };
      botState.statusCache = payload;
      return json(res, payload, 200, cors);
    } catch (err) {
      if (botState.statusCache) {
        return json(res, { ...botState.statusCache, stale: true }, 200, cors);
      }
      throw err;
    }
  }

  if (req.method === 'GET' && endpoint === '/api/auctions') {
    const auctions = await getMarketSnapshot(forceRefresh);
    return json(res, auctions.map(serializeAuction), 200, cors);
  }

  if (req.method === 'GET' && endpoint === '/api/logs') {
    return json(res, botState.log, 200, cors);
  }

  if (req.method === 'GET' && endpoint === '/api/diagnostics') {
    const web3 = getWeb3();
    const factoryAddr = getFactoryAddress();
    let factoryExists = false;
    let rawAddresses = [];

    try {
      const code = await retryRpc(() => web3.eth.getCode(factoryAddr));
      factoryExists = code !== '0x';
      if (factoryExists) {
        rawAddresses = await retryRpc(() => getFactory().methods.getDeployedCampaigns().call());
      }
    } catch (_) {}

    const auctions = await getMarketSnapshot();
    return json(res, {
      factoryAddress: factoryAddr,
      factoryExists,
      rawAddressesCount: rawAddresses.length,
      rawAddresses: rawAddresses.slice(0, 5),
      totalAuctions: auctions.length,
      validAuctions: auctions.length,
      rpcUrl: process.env.RPC_HTTP ? 'configured' : 'missing',
    }, 200, cors);
  }

  if (req.method === 'GET' && endpoint === '/api/factory-raw') {
    try {
      const addresses = await retryRpc(() => getFactory().methods.getDeployedCampaigns().call());
      return json(res, { count: addresses.length, addresses: addresses.slice(0, 10) }, 200, cors);
    } catch (err) {
      return json(res, { error: unwrapError(err) }, 500, cors);
    }
  }

  if (req.method === 'GET' && endpoint === '/api/config') {
    return json(res, getRuntimeConfig(), 200, cors);
  }

  if (req.method === 'POST' && endpoint === '/api/config') {
    const data = JSON.parse(body || '{}');
    const config = updateRuntimeConfig(data);
    logger.info('Operator config updated', config);
    return json(res, { ok: true, config }, 200, cors);
  }

  if (req.method === 'POST' && endpoint === '/api/start') {
    if (botState.running) return json(res, { ok: false, error: 'Already running' }, 200, cors);
    startAutoLoop();
    return json(res, { ok: true }, 200, cors);
  }

  if (req.method === 'POST' && endpoint === '/api/stop') {
    stopAutoLoop();
    return json(res, { ok: true }, 200, cors);
  }

  if (req.method === 'POST' && endpoint === '/api/run-once') {
    runCycle().catch((err) => logger.error('Cycle error', { error: unwrapError(err) }));
    return json(res, { ok: true }, 200, cors);
  }

  if (req.method === 'POST' && endpoint === '/api/create-auction') {
    try {
      const result = await createAuction(JSON.parse(body || '{}'));
      botState.stats.created++;
      return json(res, { ok: true, result: result.newAddress || 'simulated' }, 200, cors);
    } catch (err) {
      return json(res, { ok: false, error: unwrapError(err) }, 400, cors);
    }
  }

  if (req.method === 'POST' && endpoint === '/api/create-generated-auction') {
    const { count } = JSON.parse(body || '{}');
    try {
      const results = await createAutoGeneratedAuctions(Number(count || process.env.AUTO_GENERATE_COUNT || '1'));
      botState.stats.created += results.filter((r) => r.success).length;
      return json(res, { ok: true, results }, 200, cors);
    } catch (err) {
      return json(res, { ok: false, error: unwrapError(err) }, 400, cors);
    }
  }

  if (req.method === 'POST' && endpoint === '/api/bid') {
    const { address, amountWei } = JSON.parse(body || '{}');
    try {
      const result = await placeBid(address, BigInt(amountWei));
      botState.stats.bids++;
      return json(res, { ok: true, tx: result.transactionHash }, 200, cors);
    } catch (err) {
      await resyncNonce();
      return json(res, { ok: false, error: unwrapError(err) }, 400, cors);
    }
  }

  if (req.method === 'POST' && endpoint === '/api/finalize') {
    const { address } = JSON.parse(body || '{}');
    try {
      const result = await finalizeAuction(address);
      botState.stats.finalized++;
      return json(res, { ok: true, tx: result?.transactionHash || 'simulated' }, 200, cors);
    } catch (err) {
      return json(res, { ok: false, error: unwrapError(err) }, 400, cors);
    }
  }

  if (req.method === 'POST' && endpoint === '/api/check-winner') {
    const results = await processClosedAuctions();
    return json(res, { ok: true, results }, 200, cors);
  }

  if (req.method === 'POST' && endpoint === '/api/run-mode') {
    const { mode } = JSON.parse(body || '{}');
    try {
      await runMode(mode);
      return json(res, { ok: true, message: `Mode ${mode} executed successfully` }, 200, cors);
    } catch (err) {
      return json(res, { ok: false, error: unwrapError(err) }, 400, cors);
    }
  }

  return json(res, { error: 'Not found' }, 404, cors);
}

async function runMode(mode) {
  const { fetchAllAuctions } = require('./auctions');
  const { bidOnEligibleAuctions, finalizeAuction } = require('./bidder');
  const { processClosedAuctions } = require('./winner');
  const { startCron } = require('./autotrader');
  const { runSimulation } = require('./simulator');

  switch (mode) {
    case 'simulate':
    case 'status':
      await runSimulation();
      break;
    case 'buy': {
      const auctions = await getMarketSnapshot(true);
      for (const auction of auctions.filter((a) => !a.isActive && !a.closed && a.isManager && a.approversCount > 0)) {
        await finalizeAuction(auction.address);
      }
      const results = await bidOnEligibleAuctions(auctions.filter((a) => a.isActive));
      logger.info(`Buy mode placed ${results.filter((r) => r.success).length} bids`);
      break;
    }
    case 'sell': {
      const results = await createAuctionsFromConfig();
      logger.info(`Sell mode created ${results.filter((r) => r.success).length} auctions`);
      break;
    }
    case 'smart':
    case 'dumb': {
      const auctions = await getMarketSnapshot(true);
      for (const auction of auctions.filter((a) => !a.isActive && !a.closed && a.isManager && a.approversCount > 0)) {
        await finalizeAuction(auction.address);
      }
      const results = await bidOnEligibleAuctions(auctions.filter((a) => a.isActive), mode);
      logger.info(`${mode} mode placed ${results.filter((r) => r.success).length} bids`);
      break;
    }
    case 'auto':
      startCron();
      break;
    case 'winner':
      await processClosedAuctions();
      break;
    case 'listen':
      await startListening();
      break;
    default:
      throw new Error(`Unknown mode: ${mode}`);
  }
}

function startAutoLoop() {
  const cron = require('node-cron');
  const schedule = process.env.AUTO_TRADE_CRON || '*/2 * * * *';
  if (!cron.validate(schedule)) {
    throw new Error(`Invalid cron schedule: ${schedule}`);
  }
  botState.cronHandle = cron.schedule(schedule, runCycle);
  botState.running = true;
  ensureLiveAutomation();
  logger.info(`Bot started with cron ${schedule}`);
  runCycle();
}

function stopAutoLoop() {
  if (botState.cronHandle) {
    botState.cronHandle.stop();
    botState.cronHandle = null;
  }
  botState.running = false;
  logger.info('Bot stopped');
}

async function runCycle() {
  if (botState.cycleRunning) {
    logger.warn('Admin cycle already running - skipping overlap');
    return;
  }

  botState.cycleRunning = true;
  botState.cycleCount++;
  botState.lastCycle = new Date().toISOString();

  try {
    const auctions = await getMarketSnapshot(true);

    if (process.env.ENABLE_SELLING === 'true') {
      const created = await maintainAuctionInventory(auctions);
      botState.stats.created += created.filter((r) => r.success).length;
      botState.stats.errors += created.filter((r) => !r.success).length;
    }

    if (process.env.ENABLE_FINALIZE !== 'false') {
      for (const auction of auctions.filter((a) => !a.isActive && !a.closed && a.isManager && a.approversCount > 0)) {
        try {
          const result = await finalizeAuction(auction.address);
          if (!result?.skipped) botState.stats.finalized++;
        } catch (_) {
          botState.stats.errors++;
        }
      }
    }

    if (process.env.ENABLE_BIDDING !== 'false') {
      const results = await bidOnEligibleAuctions(auctions.filter((a) => a.isActive));
      botState.stats.bids += results.filter((r) => r.success && !r.simulated).length;
      botState.stats.errors += results.filter((r) => !r.success).length;
    }
  } catch (err) {
    botState.stats.errors++;
    logger.error('Cycle error', { error: unwrapError(err) });
  } finally {
    botState.cycleRunning = false;
  }
}

async function getMarketSnapshot(force = false) {
  const now = Date.now();
  if (!force && botState.marketCache && (now - botState.marketCacheAt) < MARKET_CACHE_TTL_MS) {
    return botState.marketCache;
  }

  const auctions = await fetchAllAuctions();
  botState.marketCache = auctions;
  botState.marketCacheAt = now;
  return auctions;
}

function ensureLiveAutomation() {
  if (botState.listenerStarted) return;
  botState.listenerStarted = true;
  startListening(() => {
    setTimeout(() => {
      runCycle().catch((err) => logger.error('Live-triggered cycle failed', { error: unwrapError(err) }));
    }, 1200);
  }).catch((err) => {
    logger.warn('Live listener unavailable for admin automation', { error: err.message });
  });
}

function serializeAuction(auction) {
  return {
    address: auction.address,
    dataDescription: auction.dataDescription,
    dataForSell: auction.dataForSell,
    minimumContribution: auction.minimumContribution.toString(),
    highestBid: auction.highestBid.toString(),
    approversCount: auction.approversCount,
    endTimeSec: auction.endTimeSec,
    secondsLeft: auction.secondsLeft,
    isActive: auction.isActive,
    isManager: auction.isManager,
    isWinner: auction.isWinner,
    amIBidding: auction.amIBidding,
    amIWinning: auction.amIWinning,
    myBid: auction.myBid.toString(),
    closed: auction.closed,
  };
}

function startAdminServer() {
  const CORS = {
    'Access-Control-Allow-Origin': `http://localhost:${PORT}`,
    'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type',
  };

  const server = http.createServer(async (req, res) => {
    if (req.method === 'OPTIONS') {
      res.writeHead(204, CORS);
      return res.end();
    }

    if (req.method === 'GET' && (req.url === '/' || req.url === '/index.html')) {
      const html = fs.readFileSync(path.join(__dirname, 'admin.html'), 'utf8');
      res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' });
      return res.end(html);
    }

    let body = '';
    req.on('data', (chunk) => { body += chunk; });
    req.on('end', async () => {
      try {
        await handleApi(req, res, body, CORS);
      } catch (err) {
        logger.error('Admin API error', { error: unwrapError(err) });
        json(res, { error: unwrapError(err) }, 500, CORS);
      }
    });
  });

  server.listen(PORT, '127.0.0.1', () => {
    logger.info(`Admin panel ready at http://localhost:${PORT}`);
  });

  return server;
}

module.exports = { startAdminServer, runCycle, startAutoLoop, stopAutoLoop, botState };
